#!/bin/bash
if [[ "$OSTYPE" == darwin* ]]; then
  pbcopy
elif [[ "$OSTYPE" == cygwin* ]]; then
  cat > /dev/clipboard
else
  if type "xclip" > /dev/null; then
    xclip -in -selection clipboard
  elif type "xsel" > /dev/null; then
    xsel --clipboard --input 
  elif [ -f "$ext_tmux_copy" ]; then
    $ext_tmux_copy
  else
    echo "clipcopy: Platform $OSTYPE not supported or xclip/xsel not installed" >&2
  fi
fi
